### PR TITLE
Remove Unneeded Header Files

### PR DESCRIPTION
**Pull request by yasithmilinda**
### Contributing checklist
- [x] Code must follow existing styling conventions
- [x] Added a descriptive commit message

### Solves issue(s)
Remove the unused, conflicting header files OTPublisher.h and OTSubscriber.h, and removed dependencies on them in OTPublisher.m and OTSubscriber.m

### CODE REVIEW

**Comment by snobear** [comment]
@yasithmilinda I think it'd be good to test this with RN < 0.60 to ensure it works with previous versions. Can you spin up a fresh project with say, 0.59 and try out your PR?

**Comment by yasithmilinda** [comment]
@snobear good idea, I'll give this a shot and update here

**Comment by yasithmilinda** [comment]
@snobear Good news, I've confirmed that this works on ios for both RN 0.58X and RN 0.59.X!

**Comment by snobear** [comment]
Hi @yasithmilinda You can close this one, since I merged it in already in #358. So once that gets merged we've got this too.

**Comment by yasithmilinda** [comment]
@snobear yeah, I forgot this one existed! I'll close it.

**Pull request closed without merging**
