### PR TITLE
add podspec for autolinking support in RN 0.6x

### PR DESCRIPTION
**Pull request by snobear**
Add podspec to support [autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) in React Native 0.6x.

Solves issue #332

### CODE REVIEW

**Comment by yasithmilinda** [comment]
Huge +1 for this PR! Thanks @snobear, hope it gets merged soon

**Comment by snobear** [comment]
Eh this podspec isn't sufficient to get opentok-react-native working with RN 0.6x. With a fresh project using [`react-native init`](https://facebook.github.io/react-native/docs/getting-started), the iOS build throws:

```
`React/RCTBridgeModule.h` file not found
```

image

I've tried a thousand different things, but not exactly sure what else we need to tweak in this library to get it working with RN 0.6. 

**Steps to Reproduce**

1. Start a new project and add opentok-react-native:

```
react-native init FreshProject
cd FreshProject
yarn add "https://github.com/snobear/opentok-react-native#add-podspec"
cd ios
pod install
cd ..
```

2. Open `<YourProjectName>.xcworkspace` contents in XCode. This file can be found in the `ios` folder of your React Native project. Click on your project in top left of Xcode so its highlighted.

3. Click `File` and `New File`

4. Add an empty swift file to your project:
    * You can name this file anything i.e: `OTInstall.swift`. This is done to set some flags in XCode so the Swift code can be used.

5. Click `Create Bridging Header` when you're prompted with the following modal: `Would you like to configure an Objective-C bridging header?`

6. Ensure you have enabled both camera and microphone usage by adding the following entries to your `Info.plist` file:

```
<key>NSCameraUsageDescription</key>
<string>Your message to user when the camera is accessed for the first time</string>
<key>NSMicrophoneUsageDescription</key>
<string>Your message to user when the microphone is accessed for the first time</string>
```

7. cd to root of your project and fire it up

```
react-native run-ios
```

From here its a bunch of header file not found errors.

I've tried tweaking the `opentok-react-native/ios/OpenTokReactNative.xcodeproj/project.pbxproj` file to remove `HEADER_SEARCH_PATHS` and then cleaning the build and xcode and reinstalling pods, but no luck. It seems like the OT's pbxproj is ignored completely. I was thinking it was overriding my projects search paths, but I guess not.

I can move this to an issue instead of a PR, but wanted to get a discussion going. Let me know if anyone has any troubleshooting ideas.

**Comment by snobear** [comment]
OK fixed the header issues by adding the required dependencies to the podspec file:

```
  s.dependency 'React'
  s.dependency 'OpenTok' 
```

Now getting the following:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_OTPublisherSwift", referenced from:
      objc-class-ref in libopentok-react-native.a(OTPublisher.o)
      l_OBJC_$_CATEGORY_OTPublisherSwift_$_RCTExternModule in libopentok-react-nativ
  "_OBJC_CLASS_$_OTSessionManager", referenced from:
      objc-class-ref in libopentok-react-native.a(OTSessionManager.o)
      l_OBJC_$_CATEGORY_OTSessionManager_$_RCTExternModule in libopentok-react-nativ
  "_OBJC_CLASS_$_OTSubscriberSwift", referenced from:
      objc-class-ref in libopentok-react-native.a(OTSubscriber.o)
      l_OBJC_$_CATEGORY_OTSubscriberSwift_$_RCTExternModule in libopentok-react-nati
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Gettin there! Tried adding JavascriptCore.Framework` under the target's Build Phases > Link Binary With Libraries per other suggestions but no luck on that.

**Comment by yasithmilinda** [comment]
Hello @snobear,

I suspect it is because you are only adding the .h and .m files in the src_files import. Maybe you should add the .swift files there too?

**Comment by yasithmilinda** [comment]
Hello, @snobear Good news, I confirmed that using ios/**/*.{h,m,swift} resolves the issue you mentioned.
However, this seems to lead to a new problem, where the two interfaces:

```@interface OTPublisher```
```@interface OTSubscriber``` 

are defined twice: One in the OpenTok.framework, and one in the opentok-react-native library.

One of these headers should be made private. @snobear or anyone, any ideas?

**Comment by yasithmilinda** [comment]
> Hello, @snobear good news, I confirmed that using
> 
> ```ruby
> s.source_files  = "ios/**/*.{h,m,swift}"
> ```
> 
> resolves the issue you mentioned! However, this seems to lead to a new problem, where the two interfaces:
> 
> ```objc
> @interface OTPublisher
> @interface OTSubscriber
> ```
> 
> are defined twice: One in the OpenTok.framework, and one in the opentok-react-native library. One of these headers should be made private. @snobear or anyone, any ideas?

My instinct is to rename the OTPublisher and OTSubscriber interfaces here to OTPublisherView and OTSubscriberView to circumvent this issue, as they both extend RCTView class anyway. But I'm not sure what implications it might have

**Comment by yasithmilinda** [comment]
Hello @snobear, I've created Issue #361 to handle the duplicate header issue. If this gets merged into master, then I bet this PR will work as expected after you set 
```podspec
s.source_files  = "ios/**/*.{h,m,swift}"
```

**Comment by th317erd** [comment]
Hey, can we please get this merged?

**Comment by snobear** [comment]
All looks good on iOS after merging the #361 to fix the duplicate headers. 

However, this has not been tested on RN <0.60, which @yasithmilinda will do to make sure those duplicate header removals don’t have a negative effect on older versions.

**Comment by yasithmilinda** [comment]
@th317erd @snobear I've just confirmed that the changes in header files in #361 do not break existing functionality in RN 0.58 and 0.59.

**Comment by snobear** [comment]
@yasithmilinda awesome! This PR should be good to merge into master then IMO.

**Comment by th317erd** [comment]
Awesome! Thank you @yasithmilinda! :)

**Comment by yasithmilinda** [comment]
> Awesome! Thank you @yasithmilinda! :)

thank you @th317erd!

**Comment by yasithmilinda** [comment]
Hello folks, can we get this feature merged?

**Comment by enricop89** [comment]
Hi guys, thank you for the great job here. 
I hope to have time next week to review it. I'm sorry for the delay.

**Comment by barunprasad** [comment]
Thank you for the work so far. Are there any updates on this?

**Comment by mhdtouban** [comment]
When are you going to release it?

**Comment by barunprasad** [comment]
Need this feature soon as we are not able to test this library on a native device without this feature. Greatly appreciate if the PR is merged.

**Comment by ggoldens** [comment]
Hi @barunprasad, sorry the delay on this. We're currently reviewing this PR.
Just by curiosity, why are you not able to test this library without this PR? If I understand it well, it's just an enhancement, not a bug fix.

**Comment by ggoldens** [comment]
@snobear maybe I'm missing a step but I'm getting this after following your steps with RN 0.61 on a fresh project.

Screen Shot 2019-11-12 at 3 55 24 PM

**Comment by barunprasad** [comment]
@ggoldens thank you for the response. We are currently on the latest version of RN 0.61.x and we constantly upgrade to the latest version which needs all libraries to move to auto linking (not use react-native link). All our dependencies have auto-linking support. You can say that for this library we can make an exception and do the manual setup. But we wanted to make sure we only add those libraries to our project which does not block us from upgrading our projects in the future. Hence the request to have this feature ready.
Anyhow, you guys have been doing great work on this. Hope to see this feature available soon.

**Comment by th317erd** [comment]
@barunprasad For now you could always do what I am doing for now: Create a `postinstall` script in your `package.json` that creates the podspec file. I created a script that scans all react-native modules, and creates a podspec for any missing podspecs. This has enabled us on our team to autolink any library.

**Comment by ggoldens** [comment]
@snobear were you able to reproduce the error I put above? thanks.

**Comment by snobear** [comment]
@ggoldens sorry been tied up. Taking a look now.

**Comment by snobear** [comment]
FYI I_was getting a new error:

```
[!] Unable to determine Swift version for the following pods:

- `opentok-react-native` does not specify a Swift version and none of the targets (`NewProject`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

but fixed by specifying `s.swift_version` in the podspec (added to this PR's branch).

**Comment by snobear** [comment]
@ggoldens I'm able to install the PR with a fresh 0.61.4 RN project. You definitely shouldn't get complaints about React being available, as the podspec has it specified as a dependency. I would double-check that `node_modules/opentok-react-native/opentok-react-native.podspec` is present and has the dependencies listed, i.e. the podspec is the same version as in this PR. There were a few updates made along the way in this discussion, so make sure you have the latest.

Also try clearing out cache as specified in the simulator, and close any running metro bundler and Xcode instances if they're running before doing a new project.

Can some other folks please try installing this w/ a new project per [install steps](https://github.com/opentok/opentok-react-native/pull/358#issuecomment-540838823)?

My system info in case its helpful:

```
$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz
    Memory: 1.05 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

**Comment by mhdtouban** [comment]
I was able to integrate @snobear PR into our project and it's working fine

**Comment by snobear** [comment]
Hi all, just checking if we can get two other reviewers to review/merge please?

**Comment by ggoldens** [comment]
@snobear, can you point this PR to the branch 0.12.2 please?

**Comment by snobear** [comment]
@ggoldens done.

**Pull request merged**
