### PR TITLE
0.16.0 to Main

### PR DESCRIPTION
**Pull request by enricop89**
- Adding CustomAudio Source with Stereo Support for `iOS` and `Android`
- Bump package.json version

### CODE REVIEW

**Review by abdulajet — APPROVED** [review]

**Review by ggoldens — COMMENTED** [review]
Thanks!! quick question, why we are using double quotes instead of simple quotes?

**Comment by enricop89** [comment]
@ggoldens sorry, I messed up with Prettier 🤣

**Review by enricop89 — COMMENTED** [review]
LGTM

**Review by ggoldens — APPROVED** [review]
LGTM

**Pull request merged**
