### PR TITLE
Android single disconnectCallback invocation, remove depracated canvas flag, prevent nulls

### PR DESCRIPTION
**Pull request by selcute**
### Contributing checklist
- [x] Code must follow existing styling conventions
- [x] Added a descriptive commit message

### Solves issue(s)

#175

### CODE REVIEW

**Comment by msach22** [comment]
@selcute Thanks for the PR! I'm not sure if this is the best way to prevent the callback issue, let me dig a little further and get back to you shortly!

**Comment by sunweiyang** [comment]
What is the status of this PR? We are also seeing this issue happening in production. (If there are mitigating steps that we could take that's independent of code changes to `opentok-react-native`, that advice would help a lot too.)

**Comment by msach22** [comment]
@sunweiyang I'm working on a fix for this. I think what's happening is that the callback is not being set to null and that we are doing `disconnectCallback = callback` after we call the disconnect method whereas we should be doing that first to prevent any race condition. 

I'll update ya'll shortly on this.

**Comment by msach22** [comment]
@sunweiyang just wanted to update you on this issue: https://github.com/opentok/opentok-react-native/issues/175#issuecomment-448816541

**Comment by msach22** [comment]
I'm closing this PR because of: https://github.com/opentok/opentok-react-native/pull/216

@selcute Thanks for your input!

**Pull request closed without merging**
