### PR TITLE
fixes #60

### LINKED ISSUE #60: Session does not fully disconnect after component is dismounted
Apparently the native application context or the javascript thread are not being reset after the video call scene is dismounted. After opening, exiting, and re-entering a call, the events from the previous session keeps executing.

Steps to simulate the error.

1. Open a call
2. Set listeners for Session, Publisher, and Subscriber and print with the random number.
3. Exit call screen
4. Start the call again

### PR DESCRIPTION
**Pull request by msach22**

### CODE REVIEW

**Comment by renanpupin** [comment]
@msach22 you changed the OTSession but forgot to remove the listeners from OTSubscriber too.
Have a good day.

**Comment by msach22** [comment]
fixes #64 as well!

**Comment by renanpupin** [comment]
@msach22 could you please publish the yarn package 0.6.0?

**Comment by msach22** [comment]
@renanpupin the 0.6.0 release has been out! The `0.6.1` package is out as well!

**Pull request merged**
