### PR TITLE
Updated SDK Version to 2.16.2

### PR DESCRIPTION
**Pull request by aslampr07**
### Contributing checklist
- [x] Code must follow existing styling conventions
- [x] Added a descriptive commit message

### Solves issue(s)

[Issue #357 ](https://github.com/opentok/opentok-react-native/issues/357)

### CODE REVIEW

**Comment by msach22** [comment]
Thanks for the PR @aslampr07. @ggoldens Could you please create an RC and merge it in there?

**Comment by aslampr07** [comment]
> 
> 
> Thanks for the PR @aslampr07. @ggoldens Could you please create an RC and merge it in there?

sorry, how do i do it?

**Comment by msach22** [comment]
@aslampr07 I've just changed the base branch to the release branch. Could you please resolve the conflicts so we can merge in the PR?

**Comment by aslampr07** [comment]
There isn't any conflict, you can merge it now.

**Comment by aslampr07** [comment]
Thank you, i have resolved the conflict.

**Comment by msach22** [comment]
Looks like the 0.12.2 branch already has the update. I'll check internally and circle back when we will release this.

**Comment by aslampr07** [comment]
Okay cool, when can i expect the 0.12.2 to be in the master?

**Comment by ggoldens** [comment]
Closing this PR since 0.12.2 already contains this update. We will release it soon. Thanks!

**Pull request closed without merging**
