### PR TITLE
0.15.0 to master

### PR DESCRIPTION
**Pull request by enricop89**
- adding Typescript support: #408 
- adding setPreferredResolution and setPreferredFrameRate methods: #434 
- Fixed android app crash with API level 29 (#456) 
- upgrade SDK to 2.18.1 (#466)

### CODE REVIEW

**Comment by enricop89** [comment]
@ggoldens @msach22 should we bump native SDK versions as well? iOS and Android to `2.18.1`.
We need to run a sanity check on this branch before updating and merging to master.

**Comment by msach22** [comment]
@enricop89 Yes, please do that!

**Comment by slauzinho** [comment]
Typescript types seem to be missing `OTSubscriberView`.

Currently, when trying to import `OTSubscriberView` it gives the error:
`Module '"opentok-react-native"' has no exported member 'OTSubscriberView'.`

**Comment by flogy** [comment]
Thank you for your work, guys! Looking forward to this release.

**Comment by deermichel** [comment]
When can we expect the release?

**Comment by msach22** [comment]
@ggoldens @enricop89 Can you please get this to the finish line?

**Review by ggoldens — APPROVED** [review]
LGTM

**Comment by flogy** [comment]
Awesome, thanks for merging!

**Pull request merged**
